### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by jiiuluo00001** [sometastycake/bufflogin#10]
Hello, I tried to write a demo

```
from bufflogin import Buff
from pysteamauth.auth import Steam
import asyncio

async def demo():
    steam = Steam(
        login='******',
        password='******',
    )
    buff = Buff(steam)
    await buff.login_to_buff()
    response: str = await buff.request('https://buff.163.com/')

if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        asyncio.run(demo())
    except KeyboardInterrupt:
        pass

```

Report this error, where did I write wrong? Thanks!
```
Traceback (most recent call last):
  File "D:\workspace_python\buffspider\buffspider\test\aaa.py", line 19, in <module>
    asyncio.run(demo())
  File "E:\software\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\software\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\workspace_python\buffspider\buffspider\test\aaa.py", line 11, in demo
    await buff.login_to_buff()
  File "D:\workspace_python\buffspider\venv\lib\site-packages\bufflogin\buff.py", line 78, in login_to_buff
    await self._steam.login_to_steam()
  File "D:\workspace_python\buffspider\venv\lib\site-packages\pysteamauth\auth\steam.py", line 334, in login_to_steam
    code = await Steam.get_steam_guard(self.shared_secret, server_time)
  File "D:\workspace_python\buffspider\venv\lib\site-packages\pysteamauth\auth\steam.py", line 75, in shared_secret
    raise ValueError('shared_secret is not specified')
ValueError: shared_secret is not specified
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001B1AAAF7D30>
transport: <_ProactorSocketTransport fd=788 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "E:\software\Python310\lib\asyncio\proactor_events.py", line 361, in write
    self._loop_writing(data=bytes(data))
  File "E:\software\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000001B1A83A65F0>
Traceback (most recent call last):
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 321, in __del__
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 316, in close
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "E:\software\Python310\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "E:\software\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "E:\software\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001B1AAAF7160>
transport: <_ProactorSocketTransport fd=796 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "E:\software\Python310\lib\asyncio\proactor_events.py", line 361, in write
    self._loop_writing(data=bytes(data))
  File "E:\software\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000001B1A83A65F0>
Traceback (most recent call last):
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 321, in __del__
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 316, in close
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "E:\software\Python310\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "E:\software\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "E:\software\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001B1AAAF69E0>
transport: <_ProactorSocketTransport fd=652 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "E:\software\Python310\lib\asyncio\proactor_events.py", line 361, in write
    self._loop_writing(data=bytes(data))
  File "E:\software\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000001B1A83A65F0>
Traceback (most recent call last):
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 321, in __del__
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 316, in close
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "E:\software\Python310\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "E:\software\Python310\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "E:\software\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "E:\software\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by sometastycake** [comment]
@jiiuluo00001 
Does your Steam account have steam guard?
